# Generated by Django 5.1.4 on 2025-01-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this user has completed the verification process.', verbose_name='verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('STORE_MANAGER', 'Store Manager'), ('FULFILLMENT_SPECIALIST', 'Fulfillment Specialist'), ('SUPPORT_AGENT', 'Support Agent'), ('WAREHOUSE_STAFF', 'Warehouse Staff'), ('ACCOUNTANT', 'Accountant'), ('B2B_PARTNER', 'B2B Partner'), ('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=50, verbose_name='user type'),
        ),
    ]
