# Generated by Django 5.1.4 on 2025-01-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
