# Generated by Django 5.1.4 on 2025-01-13 13:34

import apps.accounts.models.invitation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_company_name_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('STORE_MANAGER', 'Store Manager'), ('FULFILLMENT_SPECIALIST', 'Fulfillment Specialist'), ('SUPPORT_AGENT', 'Support Agent'), ('WAREHOUSE_STAFF', 'Warehouse Staff'), ('ACCOUNTANT', 'Accountant'), ('GLOBAL_BUYER', 'Global Buyer'), ('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=50, verbose_name='user type'),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('STORE_MANAGER', 'Store Manager'), ('FULFILLMENT_SPECIALIST', 'Fulfillment Specialist'), ('SUPPORT_AGENT', 'Support Agent'), ('WAREHOUSE_STAFF', 'Warehouse Staff'), ('ACCOUNTANT', 'Accountant'), ('GLOBAL_BUYER', 'Global Buyer'), ('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer')], max_length=50, validators=[apps.accounts.models.invitation.validate_non_customer], verbose_name='user type'),
        ),
    ]
