# Generated by Django 5.1.4 on 2024-12-15 23:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_passwordreset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordreset',
            options={},
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
