# Generated by Django 5.1.4 on 2024-12-15 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerprofile',
            table='customer_profile',
        ),
    ]
